apiVersion: v1
kind: Service
metadata:
  name: book-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/books/health
  namespace: bookstore
  labels:
    app: book-service
    app.kubernetes.io/part-of: bookstore
spec:
  type: ClusterIP
  selector:
    app: book-service
  ports:
    - name: http
      port: 8000
      targetPort: http
