apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
  namespace: bookstore
data:
  DB_HOST: "bookstore-main.cpw0c4w628w0.ap-south-1.rds.amazonaws.com"
  BOOK_SERVICE_URL: "http://book-service:8000"
