apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - rbac.yaml
  - configmap.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - book-service/deployment.yaml
  - book-service/service.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
images:
  - name: 394070775944.dkr.ecr.ap-south-1.amazonaws.com/bookstore/user-service
    newTag: 9afc83c
  - name: 394070775944.dkr.ecr.ap-south-1.amazonaws.com/bookstore/book-service
    newTag: 9afc83c
  - name: 394070775944.dkr.ecr.ap-south-1.amazonaws.com/bookstore/order-service
    newTag: 9afc83c
