apiVersion: v1
kind: ResourceQuota
metadata:
  name: bookstore-quota
  namespace: bookstore
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "4"
    limits.memory: 6Gi
    pods: "30"
    services: "10"
    services.loadbalancers: "0"
    services.nodeports: "0"
    secrets: "20"
    configmaps: "20"
    persistentvolumeclaims: "0"
